name: Generate Schemas
run-name: Generate ${{ contains(inputs.version, 'dev') && 'dev' || inputs.version }} Schemas

on:
  workflow_dispatch:
    inputs:
      version:
        description: "ESPHome version"
        required: true
        type: string

  pull_request:

jobs:
  information:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Version
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=dev" >> $GITHUB_OUTPUT
          fi

  generate-schemas:
    runs-on: ubuntu-24.04
    needs: information
    steps:
      - name: Set up Python 3.12
        id: python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
        with:
          python-version: 3.12

      - name: Checkout esphome repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1
        with:
          repository: esphome/esphome
          path: esphome
          ref: ${{ contains(needs.information.outputs.version, 'dev') && 'dev' || needs.information.outputs.version }}
          fetch-depth: 1

      - name: Install ESPHome dependencies
        working-directory: esphome
        run: |
          pip install -r requirements.txt -r requirements_test.txt
          pip install -e .

      - name: Generate language schema
        run: python esphome/script/build_language_schema.py --output-path=./schema

      - name: Checkout esphome-docs repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1
        with:
          repository: esphome/esphome-docs
          path: esphome-docs
          ref: ${{ contains(needs.information.outputs.version, 'dev') && 'next' || needs.information.outputs.version }}
          fetch-depth: 1

      - name: Add docs to language schema
        working-directory: esphome-docs
        run: |
          if [[ "${{ contains(needs.information.outputs.version, 'b') }}" == "true" ]]; then
            DEPLOY_URL="https://beta.esphome.io"
          elif [[ "${{ contains(needs.information.outputs.version, 'dev') }}" == "true" ]]; then
            DEPLOY_URL="https://next.esphome.io"
          else
            DEPLOY_URL="https://esphome.io"
          fi

          python script/schema_doc.py ../schema --deploy-url "$DEPLOY_URL" --debug-level 5

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: schema
          path: schema

  upload-schemas:
    runs-on: ubuntu-24.04
    needs: generate-schemas
    permissions:
      contents: write
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093  # v4.3.0
        with:
          name: schema
          path: schema

      - name: Zip schema
        run: |
          zip -r schema.zip schema
          mv schema.zip schema/schema.zip

      - name: Upload to gh-release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65  # v2.6.2
        if: ${{ !contains(inputs.version, 'dev') }}
        with:
          tag_name: ${{ inputs.version }}
          files: schema/schema.zip
          prerelease: ${{ contains(inputs.version, 'b') }}
          body: |
            This is the schema for ESPHome version ${{ inputs.version }}.
            It includes the language schema and the documentation schema.

      - name: Upload files to R2
        uses: ryand56/r2-upload-action@b801a390acbdeb034c5e684ff5e1361c06639e7c  # v1.4
        with:
          r2-account-id: ${{ secrets.CLOUDFLARE_R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.CLOUDFLARE_R2_SCHEMA_BUCKET_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.CLOUDFLARE_R2_SCHEMA_BUCKET_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.CLOUDFLARE_R2_SCHEMA_BUCKET }}
          source-dir: schema
          destination-dir: ${{ contains(inputs.version, 'dev') && 'dev' || inputs.version }}/
