name: Update ESPHome Schemas

on:
  workflow_dispatch:

jobs:
  update-schemas:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout esphome-schema repo
        uses: actions/checkout@v4
        with:
          ref: dev
          persist-credentials: true # important for push

      - name: Set up Python 3.9
        id: python
        uses: actions/setup-python@v5.5.0
        with:
          python-version: 3.9

      - name: Clone ESPHome repository
        run: |
          git clone --depth=1 --branch=fix-schema-gen-ci https://github.com/glmnet/esphome.git
          cd esphome
          echo "ESPHOME_COMMIT_MESSAGE=$(git log -1 --pretty=%s)" >> $GITHUB_ENV

      - name: Install ESPHome dependencies
        run: |
          cd esphome
          pip install -r requirements.txt -r requirements_optional.txt -r requirements_test.txt
          pip install -e .

      - name: Generate language schema
        run: |
          python esphome/script/build_language_schema.py --output-path=./schema

      - name: Clone ESPHome docs repository
        run: |
          git clone --depth=1 --branch=schema-2025-4 https://github.com/glmnet/esphome-docs.git

      - name: Install ESPHome docs dependencies
        run: |
          cd esphome-docs
          pip install -r requirements.txt

      - name: Add docs to language schema
        run: |
          cd esphome-docs
          python -m sphinx -a -Dextensions=github,seo,sitemap,schema_doc . _build

      - name: Commit changes to schema folder
        uses: EndBug/add-and-commit@v9
        with:
          add: "schema"
          author_name: GitHub Action
          author_email: actions@github.com
          message: "esphome: $ESPHOME_COMMIT_MESSAGE"
