name: Update ESPHome Schemas

on:
  workflow_dispatch:

jobs:
  update-schemas:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout esphome-schema repo
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Set up Python 3.9
        id: python
        uses: actions/setup-python@v5.5.0
        with:
          python-version: 3.9

      - name: Clone ESPHome repository
        run: |
          git clone --depth=1 --branch=fix-schema-gen-ci https://github.com/glmnet/esphome.git
          cd esphome
          echo "ESPHOME_COMMIT_MESSAGE=$(git log -1 --pretty=%s)" >> $GITHUB_ENV

      - name: Install ESPHome dependencies
        run: |
          cd esphome
          pip install -r requirements.txt -r requirements_optional.txt -r requirements_test.txt
          pip install -e .

      - name: Generate language schema
        run: |
          python esphome/script/build_language_schema.py --output-path=./schema

      - name: Commit changes to schema folder
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git add schema
          git diff --cached --quiet || git commit -m "esphome: $ESPHOME_COMMIT_MESSAGE"
          git push
